spring.application.name=tg-bot-rusweb

bot.name=spring228testbot
bot.token=7945101745:AAEqibTBhe355A7G2fY3uDE5OIp4yPUfGb8

python.backend.url=${PYTHON_SERVICE_URL:http://127.0.0.1:8000}
python.backend.validation_endpoint=/validate
llm.usage.daily.limit=500
logging.level.java.com.example.tgbotrusweb.integration=DEBUG
logging.level.java.net.http=DEBUG