##Channels groups ids
Channel.GERMAN=-1002412995088
Channel.ITALIAN=1
Channel.FRENCH=2
Channel.FRENCH2=4
Channel.ENGLISH=3
Channel.SPANISH=-1
Channel.ADMIN=-1002335620691
Channel.TEST=-1002412995088
##Test
Thread.GERMAN=44
Thread.ITALY=46
Thread.SPANISH=-10
Thread.FRENCH=40
Thread.ENGLISH=42
Thread.GENERAL=310