##Channels groups ids
Channel.GERMAN=-1001794635109
Channel.ITALIAN=-1001640518560
Channel.FRENCH=-1002126577376
Channel.FRENCH2=-1002056162680
Channel.ENGLISH=3
Channel.SPANISH=-1001724247014
Channel.ADMIN=-1002268177956
Channel.TEST=-0
##Thread ids for admin panel
Thread.GERMAN=2
Thread.ITALY=8
Thread.FRENCH=10
Thread.ENGLISH=4
Thread.GENERAL=6
Thread.SPANISH=185
