##Channels groups ids
Channel.ADMIN=-1002268177956
Channel.GAVROCHE=-1001915286715
Channel.WATCH_DOG=-1002032899868
Channel.SCHWARZER_HAUFEN=-1002107170355
Channel.TEST=-0
Channel.RUSSIAN=-1001704519918
Channel.RUSSIAN_LUGANSK=-1001306848001
##Thread ids for admin panel
Thread.RUSSIAN=3973
Thread.GERMAN=2
Thread.ITALY=8
Thread.FRENCH=10
Thread.ENGLISH=4
Thread.GENERAL=6
Thread.SPANISH=185